# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa080297bad781591a494b1e6947611fcc1a4673dc16ab3eb41f062d152b495cc498224e87825d7dc2f26934bea770365a79486ccd45d3e2b548e696c88b3cdf

test:
  secret_key_base: 752c5c6da0278b530b1a21ba1858a47e0d773732286c981f86e1dff68c6cee6bfa2f27e7dcbb602706072be1bbe5d184102afcd1ccffe6a40e51b38662027d0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
